[SETTINGS]
# DB에서 추출한 엑셀 파일 경로
# 스크립트와 동일한 폴더 내에 있으므로 파일명만 지정합니다.
DATA_LIST_PATH = G:\List\DataList_20260609_Add.xlsx

# 실제 파일들이 저장될(혹은 저장되어 있는) 로컬/네트워크 스토리지 루트 경로
ROOT_DIR = G:\MOLD_DATA

# Everything SDK로 원본 파일을 검색할 로컬/네트워크 경로
SEARCH_DIR = G:
