[PATH]
# 암호화된 파일이 있는 드라이브 또는 폴더 경로 (테스트용)
encrypted_drive_path = d:\00_Source\devSCKwon\insight\20260608_decrytion_fileList\mock_drive
# 결과값을 저장할 드라이브 또는 폴더 경로 (테스트용)
output_drive_path = d:\00_Source\devSCKwon\insight\20260608_decrytion_fileList\mock_output

[FILE]
# 대상 암호화 확장자
encrypted_extension = .4dhYmt2Ei
